### ISSUE TITLE
Help with Newport Delay stage

### ISSUE THREAD

**Issue by Thomas-Fischer98** [ksonod/image_delay_gui#1]
Hello, I am a master student and I am doing a project right now where I need to make a program in order to use the delay stage (DL225) from Newport. I am not very good in programming and so I mainly used your code to try to make it work. However, it is not working and so I was wondering if your code was directly working as it is on github or did you initialize the stage before using it ? Because when I run the code, the color diode is staying orange (which means that it is not initialized) and it's not green (ready to use). 

Thank you for your answer ! 
Best, 
Thomas

**Comment by ksonod** [comment]
Hello Thomas. Without seeing an error message you got, it is difficult to understand what is going on. However, I suppose it is a communication issue. 

- **Did you set a right path to a dll?** (see [L84](https://github.com/ksonod/image_delay_gui/blob/master/gui_stage_camera.m#L84))
- **Did you check which COM port you are using?** (see [L86](https://github.com/ksonod/image_delay_gui/blob/master/gui_stage_camera.m#L86))
- This repository includes GUI and Thorlabs camera stream, which might not be so relevant to what you want to do if you only want to move the Newport delay stage. If you are just interested in moving the delay stage and do not have much experience with programming, you could check [this repository](https://github.com/ksonod/controlling_devices/tree/master/basic_tools/matlab/newport_delay_stage/newport_delay_stage_control). For example, with a much simpler code ([DLS1_getversion.m](https://github.com/ksonod/controlling_devices/blob/master/basic_tools/matlab/newport_delay_stage/newport_delay_stage_control/DLS1_getversion.m)), you can check whether a right communication is established or not. **I would suggest to test with this simpler code**.

**Comment by Thomas-Fischer98** [comment]
Hello, thank you for your response ! I managed to solve the problem. I added initialization and homing commands in the code and now I am able to move the stage.
Thank you for the code, it helped a lot ! (I will cite you in my report) 
Best,

Thomas

**Comment by ksonod** [comment]
Hello Thomas. I am glad to hear the success. 
Good luck with your project.

I will close this thread.
